export type UnitDomain = "land" | "air" | "naval";

export type UnitDefinition = {
  id: string;
  name: string;
  domain: UnitDomain;
  attack: number;
  defense: number;
  speed: number;
  productionTurns: number;
  goldCost: number;
  steelCost: number;
  oilCost: number;
  special: string;
  assetFile: string;
};

export const UNIT_DEFINITIONS: UnitDefinition[] = [
  {
    id: "infantry",
    name: "Piyade",
    domain: "land",
    attack: 4,
    defense: 6,
    speed: 3,
    productionTurns: 1,
    goldCost: 120,
    steelCost: 20,
    oilCost: 0,
    special: "Şehir ve savunma savaşlarında dengeli temel birlik.",
    assetFile: "infantry.png",
  },
  {
    id: "militia",
    name: "Milis",
    domain: "land",
    attack: 2,
    defense: 4,
    speed: 2,
    productionTurns: 1,
    goldCost: 60,
    steelCost: 5,
    oilCost: 0,
    special: "Ucuz ve hızlı üretilir; açık arazide zayıftır.",
    assetFile: "militia.png",
  },
  {
    id: "special_forces",
    name: "Özel Kuvvet",
    domain: "land",
    attack: 8,
    defense: 7,
    speed: 5,
    productionTurns: 3,
    goldCost: 520,
    steelCost: 80,
    oilCost: 30,
    special: "Yüksek moral, keşif ve baskın bonusu.",
    assetFile: "special_forces.png",
  },
  {
    id: "desert_infantry",
    name: "Çöl Piyadesi",
    domain: "land",
    attack: 5,
    defense: 5,
    speed: 4,
    productionTurns: 2,
    goldCost: 210,
    steelCost: 30,
    oilCost: 5,
    special: "Çöl arazisinde hareket ve savaş bonusu.",
    assetFile: "desert_infantry.png",
  },
  {
    id: "light_tank",
    name: "Hafif Tank",
    domain: "land",
    attack: 8,
    defense: 6,
    speed: 8,
    productionTurns: 2,
    goldCost: 450,
    steelCost: 180,
    oilCost: 80,
    special: "Hızlı keşif ve zayıf hatları yarma.",
    assetFile: "light_tank.png",
  },
  {
    id: "heavy_tank",
    name: "Ağır Tank",
    domain: "land",
    attack: 13,
    defense: 12,
    speed: 4,
    productionTurns: 4,
    goldCost: 900,
    steelCost: 420,
    oilCost: 180,
    special: "Kara savaşında yüksek zırh ve ateş gücü.",
    assetFile: "heavy_tank.png",
  },
  {
    id: "fighter",
    name: "Savaş Uçağı",
    domain: "air",
    attack: 11,
    defense: 8,
    speed: 18,
    productionTurns: 3,
    goldCost: 850,
    steelCost: 220,
    oilCost: 260,
    special: "Hava üstünlüğü ve bombardıman uçaklarına karşı etkili.",
    assetFile: "fighter.png",
  },
  {
    id: "attack_helicopter",
    name: "Saldırı Helikopteri",
    domain: "air",
    attack: 10,
    defense: 6,
    speed: 12,
    productionTurns: 3,
    goldCost: 720,
    steelCost: 190,
    oilCost: 190,
    special: "Tanklara ve kara birliklerine karşı bonus.",
    assetFile: "attack_helicopter.png",
  },
  {
    id: "bomber",
    name: "Bombardıman Uçağı",
    domain: "air",
    attack: 15,
    defense: 4,
    speed: 14,
    productionTurns: 5,
    goldCost: 1300,
    steelCost: 380,
    oilCost: 420,
    special: "Şehir, fabrika ve yoğun kara birliklerine ağır hasar.",
    assetFile: "bomber.png",
  },
  {
    id: "transport_plane",
    name: "Nakliye Uçağı",
    domain: "air",
    attack: 0,
    defense: 3,
    speed: 16,
    productionTurns: 3,
    goldCost: 620,
    steelCost: 210,
    oilCost: 240,
    special: "Piyade ve özel kuvvetleri uzun mesafeye taşır.",
    assetFile: "transport_plane.png",
  },
  {
    id: "destroyer",
    name: "Destroyer",
    domain: "naval",
    attack: 9,
    defense: 8,
    speed: 9,
    productionTurns: 4,
    goldCost: 1050,
    steelCost: 500,
    oilCost: 260,
    special: "Denizaltı tespiti ve filo eskortunda güçlü.",
    assetFile: "destroyer.png",
  },
  {
    id: "battleship",
    name: "Büyük Savaş Gemisi",
    domain: "naval",
    attack: 16,
    defense: 14,
    speed: 5,
    productionTurns: 7,
    goldCost: 2100,
    steelCost: 1100,
    oilCost: 520,
    special: "Ağır deniz ateşi ve kıyı bombardımanı.",
    assetFile: "battleship.png",
  },
  {
    id: "submarine",
    name: "Denizaltı",
    domain: "naval",
    attack: 12,
    defense: 5,
    speed: 7,
    productionTurns: 5,
    goldCost: 1250,
    steelCost: 620,
    oilCost: 310,
    special: "Gizlilik ve sürpriz saldırı avantajı.",
    assetFile: "submarine.png",
  },
  {
    id: "support_ship",
    name: "Deniz Nakliye / Destek Gemisi",
    domain: "naval",
    attack: 2,
    defense: 6,
    speed: 6,
    productionTurns: 4,
    goldCost: 780,
    steelCost: 420,
    oilCost: 210,
    special: "Kara birliklerini denizden taşır ve filoya lojistik destek verir.",
    assetFile: "support_ship.png",
  },
];

export const UNIT_BY_ID = Object.fromEntries(
  UNIT_DEFINITIONS.map((unit) => [unit.id, unit])
) as Record<string, UnitDefinition>;
